# Generated by Django 2.1.5 on 2019-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190121_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_choice_field',
            field=models.TextField(choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3')], null=True),
        ),
    ]
