# Generated by Django 2.1.5 on 2019-01-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_my_choice_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='my_choice_field',
        ),
        migrations.AddField(
            model_name='post',
            name='my_genre_field',
            field=models.TextField(choices=[(1, 'Horror'), (2, 'Sci-fiction'), (3, 'Thriller'), (4, 'Action')], null=True),
        ),
    ]
