# Generated by Django 2.1.5 on 2019-01-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190122_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='my_genre_field',
        ),
        migrations.AddField(
            model_name='post',
            name='my_genre',
            field=models.TextField(choices=[('Horror', 'Horror'), ('Sci-fiction', 'Sci-fiction'), ('Thriller', 'Thriller'), ('Action', 'Action')], max_length=100, null=True),
        ),
    ]
