# Generated by Django 2.1.5 on 2019-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190122_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='my_genre',
            field=models.TextField(choices=[('Horror', 'Horror'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Action', 'Action')], max_length=100, null=True),
        ),
    ]
