# Generated by Django 2.1.5 on 2019-01-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='my_image',
            field=models.ImageField(default='default.jpg', upload_to='movie_pics'),
        ),
    ]
