# Generated by Django 2.1.5 on 2019-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190123_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='my_image',
            field=models.ImageField(default='', upload_to='movie_pics'),
        ),
    ]
