# Generated by Django 2.1.5 on 2019-01-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190124_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comm',
            name='ratings',
        ),
    ]
